<a href="https://colab.research.google.com/github/nxxk23/BasicProg_DataViz65/blob/main/Pandas_Dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

## Meta Data = Data that describes data
##CSV = Comma Separated Value
Pandas dataframe

# นำ Data เข้า 
- upload to colab
- link to google drive

## upload data to colab

In [7]:
data0 = pd.read_csv('/content/opendata_project.csv')

In [5]:
data0.head()

,row_number,project_id,name_en,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,price_min,developer_id,developer_name_en,...,facility_meeting,facility_park,facility_playground,facility_pool,facility_security,date_created,date_finish,date_updated,source,url_project
0,7880.0,5ee08d64dda791001299b2a6,Winning Residence Sukhumvit Praksa,วินนิ่ง เรสซิเดนท์ สุขุมวิท แพรกษา,1,Detached House,บ้าน,3790000.0,developer_10678,"Winning Asset Plus Co., Ltd.",...,NaN,NaN,NaN,1.0,1.0,2020-06-10 14:36:04,NaN,2020-12-04 10:32:58,baania,https://baania.com/th/project/วินนิ่ง-เรสซิเดน...
1,16689.0,project_11326,Gift Condominium,กิ๊ฟท์ คอนโดมิเนียม,2,Condo,คอนโด,1100000.0,developer_7319,"Gift Asset Land Co.,Ltd.",...,NaN,1.0,NaN,1.0,1.0,2017-10-30 15:38:48,2013-01-01 07:00:00,2020-12-04 10:49:00,baania,https://baania.com/th/project/กิ๊ฟท์-คอนโดมิเน...
2,290.0,62739c4089233e001362b001,Sanrak 9 Sukprayoon Nong Krathum,แสนรัก 9 ศุขประยูร หนองกระทุ่ม,3,Townhome,ทาวน์โฮม,0.0,developer_10510,NaN,...,NaN,NaN,NaN,NaN,NaN,2022-05-05 16:43:28,NaN,2022-05-05 17:30:03,baania,https://baania.com/th/project/แสนรัก-9-ศุขประย...
3,20719.0,project_2010,Baan Sansabai 1,บ้านแสนสบาย 1,1,Detached House,บ้าน,0.0,developer_10510,NaN,...,NaN,NaN,NaN,NaN,NaN,2016-09-05 15:32:15,1970-01-02 07:00:00,2020-12-04 10:45:31,baania,https://baania.com/th/project/บ้านแสนสบาย-1-pr...
4,199.0,project_16838,Baanpruksa Ratchapruek-345,บ้านพฤกษา ราชพฤกษ์-345,3,Townhome,ทาวน์โฮม,1930000.0,developer_1026,"Preuksa Real Estate Co.,Ltd.",...,NaN,1.0,NaN,1.0,1.0,2019-09-05 11:49:37,1970-01-02 07:00:00,2021-03-17 12:00:04,baania,https://baania.com/th/project/บ้านพฤกษา-ราชพฤก...

## link with google drive

In [16]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [21]:
data1 = pd.read_csv('/content/drive/MyDrive/BPDV65/opendata_unittype.csv')
data1.head()

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype
0,27501,unittype_9565,project_2446,2 Bedroom,2,Condo,คอนโด,NaN,37.3,2500000.0,...,1.0,1.0,NaN,NaN,NaN,NaN,2021-11-19 18:00:09,2021-11-19 17:44:45,baania,https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...
1,28777,unittype_10267,project_3543,บ้านแฝดสองชั้น Z-2,20000,Twin house,บ้านแฝด,40.0,150.0,2390000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-27 14:30:04,2022-01-27 14:22:55,baania,https://baania.com/th/project/เซน-บาย-ศิวาลัย-...
2,28865,unittype_471,project_143,1 Bedroom Type B,2,Condo,คอนโด,NaN,28.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-14 15:00:10,2022-01-14 14:40:04,baania,https://baania.com/th/project/วันพลัส-นายน์ทีน...
3,24988,unittype_19506,project_7766,Studio Floor 1-2,2,Condo,คอนโด,NaN,27.0,170000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:40:59,2020-10-14 01:06:48,baania,https://baania.com/th/project/บ้านสวนชมน้ำ-776...
4,38596,unittype_10290,project_3551,TH 3,3,Townhome,ทาวน์โฮม,NaN,182.0,2390000.0,...,1.0,1.0,NaN,NaN,2.0,NaN,2021-11-12 13:30:08,2021-02-03 12:12:54,baania,https://baania.com/th/project/เบล็สทาวน์-ศรีนค...

In [22]:
data1.head(10)

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype
0,27501,unittype_9565,project_2446,2 Bedroom,2,Condo,คอนโด,NaN,37.3,2500000.0,...,1.0,1.0,NaN,NaN,NaN,NaN,2021-11-19 18:00:09,2021-11-19 17:44:45,baania,https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...
1,28777,unittype_10267,project_3543,บ้านแฝดสองชั้น Z-2,20000,Twin house,บ้านแฝด,40.0,150.0,2390000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-27 14:30:04,2022-01-27 14:22:55,baania,https://baania.com/th/project/เซน-บาย-ศิวาลัย-...
2,28865,unittype_471,project_143,1 Bedroom Type B,2,Condo,คอนโด,NaN,28.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-14 15:00:10,2022-01-14 14:40:04,baania,https://baania.com/th/project/วันพลัส-นายน์ทีน...
3,24988,unittype_19506,project_7766,Studio Floor 1-2,2,Condo,คอนโด,NaN,27.0,170000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:40:59,2020-10-14 01:06:48,baania,https://baania.com/th/project/บ้านสวนชมน้ำ-776...
4,38596,unittype_10290,project_3551,TH 3,3,Townhome,ทาวน์โฮม,NaN,182.0,2390000.0,...,1.0,1.0,NaN,NaN,2.0,NaN,2021-11-12 13:30:08,2021-02-03 12:12:54,baania,https://baania.com/th/project/เบล็สทาวน์-ศรีนค...
5,30766,unittype_8026,project_2694,Luciano Grand,1,Detached House,บ้าน,70.5,198.0,11700000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:43,2020-10-14 19:35:20,baania,https://baania.com/th/project/คาซ่า-แกรนด์-ตาก...
6,33193,unittype_23233,project_7531,อาคารพาณิชย์สามชั้น,4,Commercial,อาคารพาณิชย์,NaN,180.0,2990000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:46:42,2020-10-15 15:13:41,baania,https://baania.com/th/project/บ้านชมดาว-7531/อ...
7,1666,unittype_14501,project_5799,บ้านเดี่ยวสองชั้น Type A,1,Detached House,บ้าน,NaN,NaN,3300000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:36:59,2020-10-14 00:40:37,baania,https://baania.com/th/project/บ้านชัยพฤกษ์-บาง...
8,41823,6215b4a7a441d30014e1f02f,6215b1cfc1620300140bc087,บ้านเดี่ยวชั้นเดียว Type C,1,Detached House,บ้าน,NaN,80.0,990000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-02-23 12:00:12,2022-02-23 11:14:31,baania,https://baania.com/th/project/เฌอลินน์ดา-ซำสูง...
9,34458,unittype_34564,project_14884,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:45:13,2020-10-14 22:16:17,baania,https://baania.com/th/project/บ้านลีลาวดี-บ้าน...

In [23]:
data1.tail(10)

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype
42615,36172,unittype_34140,project_14663,2 Bedroom,2,Condo,คอนโด,NaN,60.0,3500000.0,...,1.0,NaN,NaN,NaN,NaN,NaN,2022-02-28 15:30:05,2022-02-28 14:43:35,baania,https://baania.com/th/project/พลัส-คอนโด-โคราช...
42616,28981,unittype_25373,project_10133,บ้านเดี่ยวสองชั้น,1,Detached House,บ้าน,NaN,200.0,NaN,...,1.0,1.0,NaN,NaN,1.0,NaN,2021-11-12 13:20:09,2020-10-14 00:49:06,baania,https://baania.com/th/project/ระยองการ์เด้นฮิล...
42617,35109,unittype_1459,project_711,บ้านแสงรุ่ง,3,Townhome,ทาวน์โฮม,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:36:46,2020-10-14 00:39:29,baania,https://baania.com/th/project/บ้านแสงรุ่ง-711/...
42618,22299,unittype_13674,project_5356,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,NaN,130.0,36500000.0,...,NaN,NaN,1.0,NaN,NaN,NaN,2020-12-04 10:38:03,2020-10-14 00:47:50,baania,https://baania.com/th/project/บ้านศุธาวัลย์-53...
42619,11944,unittype_34884,project_15005,Ametrine,1,Detached House,บ้าน,NaN,353.0,23590000.0,...,1.0,1.0,1.0,1.0,1.0,NaN,2022-06-03 01:00:11,2022-06-03 00:51:19,baania,https://baania.com/th/project/เศรษฐสิริ-แจ้งวั...
42620,37109,unittype_38508,project_16864,Canola,1,Detached House,บ้าน,NaN,157.0,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,2021-11-12 13:22:37,2020-10-14 10:05:42,baania,https://baania.com/th/project/อิคอนเนเจอร์-พระ...
42621,14,unittype_14016,project_5275,Grandeur,1,Detached House,บ้าน,NaN,223.0,7490000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:36:32,2020-10-14 00:37:51,baania,https://baania.com/th/project/คาซ่า-วิลล์-ราชพ...
42622,41009,617bde1687dd2300149d2195,617bdd47f62011001350de07,Grande,3,Townhome,ทาวน์โฮม,NaN,133.0,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:34:17,2021-10-29 18:43:09,baania,https://baania.com/th/project/เดอะริคโค้-ทาวน์...
42623,9333,unittype_37375,project_16389,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,NaN,180.0,3200000.0,...,NaN,1.0,NaN,NaN,NaN,NaN,2020-12-04 10:42:26,2020-10-14 19:30:46,baania,https://baania.com/th/project/ณรงค์กิจ-รามอินท...
42624,780,unittype_17011,project_6762,บ้านธารา,1,Detached House,บ้าน,NaN,170.0,3790000.0,...,1.0,1.0,NaN,NaN,NaN,NaN,2021-11-12 13:19:43,2020-10-14 00:41:39,baania,https://baania.com/th/project/วราสิริ-รังสิต-ด...

In [24]:
data1.shape

(42625, 27)